# Generated by Django 4.2 on 2026-01-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_availability_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category the doctor belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctorcategory'),
        ),
    ]
